apiVersion: v1  
data:  
  password: dGVzdA==
kind: Secret  
metadata:  
  creationTimestamp: "2022-02-02T08:47:13Z"
  name: mysql-secrets
  namespace: mysql
  resourceVersion: "1167"
  selfLink: /api/v1/namespaces/mysql/secrets/mysql-secret
  uid: 0f5632c9-e58d-40aa-95d3-a1980ddb487b
type: Opaque
